name: CICD

on:
  workflow_dispatch:
   inputs:
    enviroment:
     description: this is enviroment value where this workflow runs
     default: 'dev'
     required: true
     type: choice
     options:
      - dev
      - production
      - staging
   

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the containers
        run: echo "Testing the containers"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "docker compose deployed the app"
