name: python lint

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: flake8 app.py
<<<<<<< HEAD
         
        
=======
        
>>>>>>> 6f5f4d93467f4280d8c3fdb21da4e41c28b4ab62
