name: python lint

on:
  push:
    branches: [main]

jobs:
  
  validate:
    runs-on: ubuntu-latest

    
steps: 
  - name: checkout code
    uses: action/checkout@v4

  - name: setupy python
    uses: action/setups-python@v4
    with:
      python-version: "3.12"

  - name: install dependencies
    uses: pip install -r requirements.txt

  - name: run linter
    run: flake8 app.py