name: python lint

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
=======
        python-version: ["3.9", "3.10", "3.11", "3.12"]
>>>>>>> 9400289b1d40a7c47f02cc787c722f3dcc833bfb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
<<<<<<< HEAD
          pip install -r requirements.txt
          pip install flake8

      - name: Run linter
        run: flake8 .
=======
          pip install flake8

      - name: Run linter
        run: flake8 . || true
>>>>>>> 9400289b1d40a7c47f02cc787c722f3dcc833bfb
